name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      -
        name : Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      
      -
        name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x                    
      -
        name: Api Install dependencies
        run: dotnet restore "./SemVer/SemVer.csproj"                            
      -
        name: Api Build
        run: dotnet build "./SemVer/SemVer.csproj" --configuration Release --no-restore      
         
  publish:
    needs: build
    if: ${{ (github.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: sharpgl
          extra-files: |
                      SemVer/SemVer.csproj